Milestone 3: Game logic
carloso0114/rubytic-tac-toe pull request #8
Opened 2020-12-24 18:06 UTC by carloso0114

In this milestone we develop a the logics of the game, based on conditions that checks for the player names, moves, and if the player win, loose or if its a draw. Asking to start again if the user wants to keep playing.

2020-12-24 20:49 UTC, elmejdki requested changes
# status: require changes :recycle: 

Great job guys :100:, you have a wonderful job on this project :clap: :clap: :clap: :clap:, you still have only some minor changes :hammer: :hammer_and_pick: :toolbox: to get it approved :checkered_flag:.

Please check the comments below:
:point_down: :point_down: :point_down: :point_down: :point_down:

## Required Changes:

- [x] Remove the .gitkeep file from the lib directory.
- [x] Please add a descriptive Readme to your project.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you have any questions please don't hesitate to contact me on slack._

2020-12-24 20:49 UTC, elmejdki commented on lib/methods.rb
> +                |_____|_____|_____|"
There should be no print or puts outside of main.rb

2020-12-24 20:49 UTC, elmejdki commented on lib/player.rb
> +  attr_accessor :name, :symbol
change attr_accessor to attr_reader cause you don't need to write the name and symbol you are just reading.

2020-12-30 13:01 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @carloso0114  & @Varun2323**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2020-12-30 15:35 UTC, merged